### ISSUE TITLE
arviz update to version 0.18.0

### ISSUE THREAD

**Issue by spyros-lytras** [Wytamma/episodic#11]
First off, great work on the package it's awesome! 

I tried it out and encountered some problems with the plotting steps (job ids 8 onwards) and traced that back to the version of arviz being a bit faulty. started off with 
`ImportError: cannot import name 'gaussian' from 'scipy.signal' (.conda/6ecab6df69d5c1ed51570e13936bce74_/lib/python3.9/site-packages/scipy/signal/__init__.py)` in job id 8 and followed by some other incompatibilities.

I fixed it quite easily by updating the python version of the arviz conda environment from `3.9` to `3.10` (required for the latest version of arviz), updating arviz to version `0.18.0` and installing some extra required packages (`bokeh` and `typer`). 

Probably worth implementing this in the core package, unless this is somehow a problem unique to my installation! 

Code: 

```shell
episodic env activate arviz

conda install python=3.10

pip install arviz==0.18.0

pip install bokeh
pip install typer

exit
```

**Comment by Wytamma** [comment]
Thanks @spyros-lytras! Yes looks alike there was un unpinned dep. I'll fix it now.

**Comment by Wytamma** [comment]
pinned in 277932d
